apiVersion: apps/v1
kind: Deployment
metadata:
  name: searching_with_elastic_search-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: searching_with_elastic_search-api
  template:
    metadata:
      labels:
        app: searching_with_elastic_search-api
    spec:
      containers:
        - name: searchingwithelasticsearch-api
          image: searchingwithelasticsearch-api:latest
          ports:
            - hostPort: 7059
              containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
          ports:
            - containerPort: 9200
              name: http
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.9.2
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
      volumes:
        - name: kibana-config
          persistentVolumeClaim:
            claimName: kibana-config-pvc